name:                generic-persistence
version:             0.7.1.0
github:              "thma/generic-persistence"
license:             BSD3
author:              "Thomas Mahler"
maintainer:          "thma@apache.org"
copyright:           "2023,2024 Thomas Mahler"
category:            Database
synopsis:            Database persistence using generics

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/thma/generic-persistence#readme>

language: GHC2021    # See https://ghc-proposals.readthedocs.io/en/latest/proposals/0380-ghc2021.html
tested-with: GHC==9.2, GHC==9.4, GHC==9.6, GHC==9.8, GHC==9.10, GHC==9.12

default-extensions:
- DuplicateRecordFields
- DeriveAnyClass
- DerivingStrategies
- OverloadedRecordDot
- TemplateHaskell
- QuasiQuotes
- LambdaCase
- DataKinds

dependencies:
- base >= 4.7 && < 5
- convertible
- HDBC
- generic-deriving
- resource-pool
- raw-strings-qq
- template-haskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  generic-persistence-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generic-persistence
    - hspec
    - hspec-discover
    - QuickCheck
    - HDBC-sqlite3 #>= 2.3.3.1
    - HDBC-postgresql #>= 2.5.0.1
    - text
    - hspec-junit-formatter
    verbatim:
      build-tool-depends:
        hspec-discover:hspec-discover == 2.*